<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>">
    <li class="form-alt">
        <p>
            <?php
            $launch_time_string = Mage::getStoreConfig( 'payment/HummPayments/launch_time' );
            $is_after           = ( time() - strtotime( $launch_time_string ) >= 0 );
            if ( $is_after && Mage::getStoreConfig( 'payment/HummPayments/specificcountry' ) == 'AU' ) {
                ?>
                <img src="<?php echo Mage::getDesign()->getSkinUrl( "images/Humm/humm-logo.png" ) ?>"
                     style="width:auto;height:16px;margin-right:6px;display:inline;"/>
                <strong> the smarter way to pay.</strong><br>Shop today, pay over time. 5 easy fortnightly payments.
                <?php
            } else {
                ?>
                <img src="<?php echo Mage::getDesign()->getSkinUrl( "images/Humm/oxipay-logo.png" ) ?>"
                     style="width:auto;height:16px;margin-right:6px;display:inline;"/>
                <strong> the smarter way to pay.</strong><br>Shop today, pay over time. 4 easy fortnightly payments.
                <?php
            }
            ?>
        </p>
    </li>
</ul>